In [1]:
import numpy as np
import torch


In [2]:
n_batch = 5
r_weights = torch.ones(3, 9)
print(torch.multinomial(r_weights, n_batch, replacement=True))

r_weights = torch.ones(9, 3)
print(torch.multinomial(r_weights, n_batch, replacement=True))

n_ones = 5
r_weights = torch.ones(n_batch, 3)
print(torch.multinomial(r_weights, n_ones, replacement=True))

tensor([[8, 2, 2, 5, 8],
        [2, 1, 2, 4, 1],
        [3, 2, 7, 2, 8]])
tensor([[0, 2, 2, 2, 1],
        [1, 2, 1, 1, 2],
        [2, 0, 1, 1, 2],
        [0, 0, 0, 1, 0],
        [1, 0, 0, 1, 1],
        [2, 2, 0, 0, 0],
        [0, 1, 2, 1, 0],
        [0, 0, 0, 0, 2],
        [0, 2, 0, 1, 2]])
tensor([[1, 1, 1, 0, 2],
        [0, 1, 2, 2, 1],
        [2, 0, 2, 1, 2],
        [1, 0, 1, 1, 2],
        [2, 0, 1, 0, 2]])


In [3]:
T_stim = 2
dt = 0.5
stim_inds = torch.arange(int(T_stim / dt))
stim_len = int(T_stim / dt)
n_batch = 5
stim_wts = torch.ones(n_batch, 12)
n_ints = 2
stim_times = torch.multinomial(stim_wts, n_ints) + 10
# print(torch.einsum('b, bl -> bl', stim_times[:, 0], stim_inds.repeat(n_batch, 1)))
print(stim_inds.repeat(n_batch, 1).shape)
print(stim_times[:, 0].view(n_batch, -1).repeat(1, stim_len) + torch.arange(stim_len))
print(stim_times[:, 0].view(n_batch, -1).repeat(1, stim_len) + torch.arange(stim_len)+2)


torch.Size([5, 4])
tensor([[11, 12, 13, 14],
        [17, 18, 19, 20],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [19, 20, 21, 22]])
tensor([[13, 14, 15, 16],
        [19, 20, 21, 22],
        [15, 16, 17, 18],
        [23, 24, 25, 26],
        [21, 22, 23, 24]])


In [4]:
n_batch = 5
n_ints = 2
n_times = 12
stim_wts = torch.ones(n_batch, n_times)

stim_times = torch.multinomial(stim_wts, n_ints)
r_stim = torch.zeros(n_batch, n_times)
r_stim[:, stim_times] = 1
print(stim_times)
print(r_stim)

r_stim = torch.zeros(n_batch, n_times)
stim_times = torch.zeros(n_batch, n_ints)
for b in range(n_batch):
    # Define an odor (CS) for each trial
    r_inds = torch.multinomial(torch.ones(n_times), n_ints)
    stim_times[b, :] = r_inds
    r_stim[b, r_inds] = 1
print(stim_times)
print(r_stim)


tensor([[ 2, 11],
        [ 9, 10],
        [ 1,  8],
        [ 5,  7],
        [ 3,  2]])
tensor([[0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.]])
tensor([[10.,  1.],
        [ 0.,  3.],
        [ 5., 11.],
        [ 8.,  4.],
        [ 9.,  4.]])
tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.]])


In [5]:
T_int = 30
T_stim = 2
time_int = torch.arange(0, T_int + dt/10, dt)
dt = 0.5
stim_inds = torch.arange(int(T_stim / dt))
stim_len = int(T_stim / dt)
n_batch = 5
stim_wts = torch.ones(n_batch, 12)
n_ints = 2
stim_times = torch.multinomial(stim_wts, n_ints) + 10
time_CS = torch.zeros(n_batch, time_int.shape[0])
print(time_CS.shape)
# print(torch.einsum('b, bl -> bl', stim_times[:, 0], stim_inds.repeat(n_batch, 1)))
# print(stim_inds.repeat(n_batch, 1).shape)
stim_inds = stim_times[:, 0].view(n_batch, -1).repeat(1, stim_len) + torch.arange(stim_len)
print(stim_inds.shape)
print(stim_inds)
# print(stim_times[:, 0].view(n_batch, -1).repeat(1, stim_len) + torch.arange(stim_len))
# print(stim_times[:, 0].view(n_batch, -1).repeat(1, stim_len) + torch.arange(stim_len)+2)
print(time_CS.shape)
# twoD_inds = torch.tensor([[torch.arange(time_CS.shape[0])], [stim_inds]])
# print(twoD_inds)
print(time_CS.shape)
print(time_CS[:, torch.tensor([3, 5, 16, 24, 34, 40])])
pos_inds = torch.tensor([1, 3, 4])
pos_inds = torch.arange(3) + 1
print(time_CS[:3, stim_inds[:3, :]])
# print(time_CS[pos_inds, stim_inds[pos_inds, :]])
time_CS[:, stim_inds] = 1
print(time_CS)


torch.Size([5, 61])
torch.Size([5, 4])
tensor([[17, 18, 19, 20],
        [12, 13, 14, 15],
        [19, 20, 21, 22],
        [15, 16, 17, 18],
        [13, 14, 15, 16]])
torch.Size([5, 61])
torch.Size([5, 61])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        

In [6]:
T_int = 20
T_stim = 2
dt = 0.5
time_int = torch.arange(0, T_int + dt/10, dt)
n_batch = 7
stim_len = int(T_stim / dt)

n_KC = 10
n_ones = int(n_KC * 0.5)
KC_wts = torch.ones(n_batch, n_KC)
r_KC_inds = torch.multinomial(KC_wts, n_ones)
r_KC = torch.zeros(n_batch, n_KC)

n_ext = 2
ext_wts = torch.ones(n_batch, n_ext)
cs_trials = torch.multinomial(torch.ones(2), n_batch, replacement=True)
print(cs_trials)
r_ext = torch.multinomial(ext_wts, n_ext)
r_ext[cs_trials == 0] = 0
print(r_ext)

for b in range(n_batch):
    r_KC[b, r_KC_inds[b, :]] = 1
# print(r_KC)
time_CS = torch.zeros(n_batch, time_int.shape[0])
time_US = torch.zeros_like(time_CS)

stim_wts = torch.ones(n_batch, 12)
n_ints = 2
stim_times = torch.multinomial(stim_wts, n_ints, replacement=True) + 10
# stim_times = torch.multinomial(torch.ones(n_batch), 12, replacement=True) + 10
# print(stim_times)
time_CS = torch.zeros(n_batch, time_int.shape[0])
for b in range(n_batch):
    stim_inds = stim_times[b, 0] + torch.arange(stim_len)
    time_CS[b, stim_inds] = 1
    stim_inds = stim_times[b, 0] + torch.arange(stim_len) + stim_len
    time_US[b, stim_inds] = 1
# print(time_CS)
# print(time_US)
# print(r_KC.shape)
# print(time_CS.shape)
# print(time_CS.repeat(n_KC, 1, 1).shape)
r_KCt = torch.einsum('bm, mbt -> bmt', r_KC, time_CS.repeat(n_KC, 1, 1))
# print(r_KCt.shape)
# print(r_KCt[0])

r_extt = torch.einsum('bm, mbt -> bmt', r_ext, time_US.repeat(n_ext, 1, 1))
print(r_extt[0])


tensor([1, 0, 0, 1, 1, 0, 1])
tensor([[1, 0],
        [0, 0],
        [0, 0],
        [0, 1],
        [1, 0],
        [0, 0],
        [1, 0]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.]])


In [7]:
py_list = [[1.,2.,3.,4.],[5.,6.,7.,8.],[9.,10.,11.,12.]]
pt_tensor_from_list = torch.FloatTensor(py_list)
print(pt_tensor_from_list)

iters = 5
my_ls = []
for i in range(iters):
    A = torch.rand(16).view(4, -1)
#     my_ls += A
    my_ls.append(A)
#     my_ls.append(A.numpy())
#     A = np.random.rand(4, 4)
#     my_ls.append(A)
    
print(my_ls)
# print(np.asarray(my_ls).shape)
# print(np.asarray(my_ls))
print(torch.stack(my_ls).shape)


tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
[tensor([[0.4306, 0.3552, 0.7308, 0.2932],
        [0.1756, 0.0096, 0.1338, 0.8588],
        [0.9297, 0.6289, 0.0091, 0.2579],
        [0.0057, 0.1262, 0.7155, 0.6931]]), tensor([[0.4301, 0.9561, 0.7288, 0.8604],
        [0.9730, 0.1772, 0.2492, 0.3134],
        [0.4161, 0.0846, 0.5165, 0.7254],
        [0.0722, 0.6971, 0.4050, 0.4315]]), tensor([[0.8838, 0.0145, 0.4630, 0.4911],
        [0.6043, 0.2485, 0.0448, 0.0069],
        [0.9939, 0.2855, 0.3718, 0.2693],
        [0.5466, 0.7837, 0.9697, 0.3258]]), tensor([[0.7507, 0.9585, 0.0553, 0.2755],
        [0.6489, 0.6341, 0.8333, 0.1454],
        [0.9052, 0.5941, 0.2755, 0.4124],
        [0.2473, 0.0685, 0.7587, 0.0490]]), tensor([[0.9054, 0.3725, 0.0033, 0.5573],
        [0.4726, 0.3776, 0.6204, 0.1559],
        [0.3783, 0.6802, 0.8591, 0.9252],
        [0.5386, 0.7868, 0.7770, 0.1042]])]
torch.Size([5, 4, 4])


In [8]:
omit_inds = torch.rand(9)>0.5
p_omit_CS = torch.rand(9)>0.5
p_omit_US = torch.rand(9)<0.5
omit_CS_inds = torch.logical_and(omit_inds, p_omit_CS)
omit_US_inds = torch.logical_and(omit_inds, p_omit_US)


In [9]:
print(1 % 2)
print(2 % 2)
print(-torch.log(torch.rand(1)) / (2/200))
list1 = [[], [], [], []]
print(len(list1))
print(torch.multinomial(torch.ones(3, 4), 6, replacement=True))


1
0
tensor([86.0667])
4
tensor([[3, 2, 2, 1, 0, 0],
        [2, 3, 1, 1, 1, 1],
        [1, 2, 2, 1, 2, 1]])


In [10]:
T_int = 200
n_batch = 4
n_odors = 2
n_KC = 200
n_ones = int(0.05 * n_KC)
stim_rate = 2 / T_int
# Define the interspike intervals and odor patterns for two CS+ and two CS- stimuli
# stim_times = [CS+ list, CS2+ list, CS- list, CS- list]
stim_times = [[] for i in range(n_odors)]
# Initialize an array to store odors for each batch
CS_inds = torch.zeros(n_batch, n_odors, n_ones)
for i in range(n_odors):
    # Define odors
    CS_inds[:, i, :] = torch.multinomial(torch.ones(n_batch, n_KC), n_ones)

    # Calculate stimulus presentation times for each odor
    last_time = torch.zeros(n_batch)
    while True:
        stim_isi = -torch.log(torch.rand(n_batch)) / stim_rate
        next_time = last_time + stim_isi
        print(next_time)
        if torch.min(next_time) < T_int:
            # Stimulus times are indices (not times)
            stim_times[i].append((next_time / dt).int())
            last_time += stim_isi
        else:
            break
    print(stim_times[i])
    print('')
print(CS_inds)

print(len(stim_times[0]))
print(stim_times[0][0].shape)
for b in range(n_batch):
    for n in range(n_odors):
        for t in stim_times[n][b]:
            if t < 400:
                print(t)
        print('')

tensor([81.1770, 35.9734, 47.1435, 19.7390])
tensor([ 97.0150, 617.0800,  47.8267, 156.4510])
tensor([128.6273, 729.5829,  70.7547, 294.7000])
tensor([130.3547, 831.8027, 236.7134, 443.3034])
tensor([168.8044, 873.5555, 317.3083, 639.4623])
tensor([228.3436, 945.6755, 405.1509, 807.6152])
[tensor([162,  71,  94,  39], dtype=torch.int32), tensor([ 194, 1234,   95,  312], dtype=torch.int32), tensor([ 257, 1459,  141,  589], dtype=torch.int32), tensor([ 260, 1663,  473,  886], dtype=torch.int32), tensor([ 337, 1747,  634, 1278], dtype=torch.int32)]

tensor([ 8.3644, 12.3815, 95.9616, 78.1212])
tensor([ 26.0338, 132.0265, 117.1223, 171.1155])
tensor([130.2218, 149.7502, 244.5762, 362.4419])
tensor([179.6645, 278.7241, 429.0509, 443.2623])
tensor([281.8581, 330.0622, 587.9724, 456.9820])
[tensor([ 16,  24, 191, 156], dtype=torch.int32), tensor([ 52, 264, 234, 342], dtype=torch.int32), tensor([260, 299, 489, 724], dtype=torch.int32), tensor([359, 557, 858, 886], dtype=torch.int32)]

tensor([

In [11]:
def my_test1(g, **kwargs):
    # call my_test2
    my_test2(**kwargs)
#     print('printing string: {}'.format(string))
    print('printing string: {}'.format(kwargs['string']))
    
def my_test2(nps=False, **kwargs):
    if nps:
        print('It worked')
    else:
        print('It also worked')
#     print('printing string: {}'.format(kwargs['string']))

my_test1(3, string='this', nps=True)
my_test1(3, string='this')
my_test1(3, string='')


It worked
printing string: this
It also worked
printing string: this
It also worked
printing string: 


In [12]:
from time import time

start_time = time()
n_odors = 4
n_batch = 30
n_epoch = 5000
dt = 0.5
T_int = 200
T_stim = 2
stim_rate = 2 / T_int

# Initialize stimulus presentation times array
stim_times = [0] * n_epoch

# Generate a list of stimulus presentation times for each trial
for e in range(n_epoch):
    batch_times = [0] * n_batch
    for b in range(n_batch):
        odor_times = [0] * n_odors
        for i in range(n_odors):
            trial_times = []
            last_time = 0
            while True:
                stim_isi = -torch.log(torch.rand(1)) / stim_rate
                next_time = last_time + stim_isi
                if next_time < (T_int - 2 * T_stim):
                    # Stimulus times are indices (not times)
                    trial_times.append((next_time / dt).int())
                    last_time += stim_isi
                # Ensure at least one presentation of each stimuli
                elif last_time == 0:
                    continue
                else:
                    break
            odor_times[i] = trial_times
        batch_times[b] = odor_times
    stim_times[e] = batch_times

print(time() - start_time)


104.56278157234192


In [13]:
print(torch.randint(10, (1,)))
print(torch.tensor([1, 0]))
print([None])
print(torch.tensor([1, 0]).repeat(5, 1))
lst = [None, 4, None]
for i in range(len(lst)):
    print(lst[i])
odor_inds = torch.multinomial(torch.ones(4, 10), 2)
print(odor_inds.shape)


tensor([5])
tensor([1, 0])
[None]
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0]])
None
4
None
torch.Size([4, 2])


In [14]:
r_kc = torch.zeros(6, 8)
r_kc2 = torch.zeros_like(r_kc)
kc_inds = torch.multinomial(torch.ones_like(r_kc), 2)
new_inds = torch.multinomial(torch.ones_like(r_kc), r_kc.shape[1])
for i in range(r_kc.shape[0]):
    kc_inds = torch.multinomial(torch.ones(r_kc.shape[1]), 2)
    r_kc[i, kc_inds] = 1
    new_inds = torch.multinomial(torch.ones(r_kc.shape[1]), r_kc.shape[1])
    r_kc2[i, :] = r_kc[i, new_inds]
print(r_kc)
print(r_kc2)
print(r_kc[1, :].sum())
new_odor = torch.multinomial(torch.ones(r_kc.shape[1]), r_kc.shape[1])
print(new_odor)
print(type(sum(r_kc[1, :])))


tensor([[0., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 1., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 1., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 1., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0., 0., 1., 0.]])
tensor(2.)
tensor([7, 6, 3, 4, 0, 2, 5, 1])
<class 'torch.Tensor'>


In [15]:
# A = torch.rand(4, 6)
# B = torch.rand(4, 6)
# C = torch.stack((A, B), dim=0)
# print(C.shape)
all_Wts = []
for tr in range(3):
    Wts = []
    wts = []
    for i in range(2):
        Wts_int = []
        wts_int = []
        for i in range(5):
            Wts_int.append(torch.rand(1, 4, 4))
            wts_int.append(torch.rand(1, 4, 4))
        Wts += Wts_int
        wts += wts_int

    Wts_trial = torch.stack(Wts, dim=-1).detach()
    print(Wts_trial.shape)
    all_Wts.append(Wts_trial)

print(all_Wts[-1][:, :, :, -1].shape)


torch.Size([1, 4, 4, 10])
torch.Size([1, 4, 4, 10])
torch.Size([1, 4, 4, 10])
torch.Size([1, 4, 4])


In [16]:
# Initialize list
time_CS = []
time_US = []

# Run trials
time1 = torch.arange(5) / 1.
time2 = torch.arange(5) / 2.
time3 = torch.arange(5) / 4.
stim_ls1 = [[time1], time3]
# stim_ls2 = [[time1, time2], time3]
stim_ls2 = [[time2], time3]
stim_ls3 = [[time1], time3]

# Store trial info
time_CS.append(stim_ls1[0])
time_CS.append(stim_ls2[0])
time_CS.append(stim_ls3[0])
time_US.append(stim_ls1[1])
time_US.append(stim_ls2[1])
time_US.append(stim_ls3[1])

max_len_CS = 2
max_len_US = 1
n_int = len(time_CS)
t_len = time_CS[0][0].shape[0]

# # Stack into array
# US_store = torch.cat(time_US)
# # print(US_store)
# if max_len_CS == 1:
#     trial_CSs = torch.cat(time_CS)
# else:
#     trial_CSs = []
#     t_len = time_CS[0][0].shape[0]
#     for i in range(max_len_CS):
#         time = torch.zeros(t_len * n_int)
#         for j in range(n_int):
#             try:
#                 time[j*t_len:(j+1)*t_len] = time_CS[j][i]
#             except IndexError:
#                 pass
#         trial_CSs.append(time)
        
# if max_len_US == 1:
#     trial_USs = torch.cat(time_US)
# else:
#     trial_USs = []
#     for i in range(len(time_US)):
#         time = time_US[i][0]
#         for j in range(1, 2):
#             try:
#                 time = torch.cat((time, time_US[i][j]))
#             except IndexError:
#                 time = torch.cat((time, torch.zeros_like(time_US[i][0])))
#         trial_USs.append(time)
    
trial_CSs = []
for i in range(max_len_CS):
    time = torch.zeros(t_len * n_int)
    for j in range(n_int):
        try:
            time[j*t_len:(j+1)*t_len] = time_CS[j][i]
        except IndexError:
            pass
    trial_CSs.append(time)
trial_USs = []
for i in range(max_len_US):
    time = torch.zeros(t_len * n_int)
    for j in range(n_int):
        try:
            time[j*t_len:(j+1)*t_len] = time_US[j][i]
        except IndexError:
            pass
    trial_USs.append(time)
    
print(trial_USs)
print(trial_CSs)


[tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]
[tensor([0.0000, 1.0000, 2.0000, 3.0000, 4.0000, 0.0000, 0.5000, 1.0000, 1.5000,
        2.0000, 0.0000, 1.0000, 2.0000, 3.0000, 4.0000]), tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]


In [17]:
A = torch.tensor([0, 0, 1, 1, 0, 1, 0])
print((A == 1).nonzero().squeeze())


tensor([2, 3, 5])


In [27]:
n_seed = 12345678
gen = torch.Generator()
gen = gen.manual_seed(n_seed)
torch.manual_seed(n_seed)
n_mbon = 2
n_recur = 4
sqrt2 = torch.sqrt(torch.tensor(2, dtype=torch.float))
mean_mbon = torch.zeros((n_recur, n_mbon))
W_mbon = torch.normal(mean_mbon, torch.sqrt(1 / (sqrt2 * n_mbon)),
                              generator=None)
print(W_mbon)
print(torch.randn(5))


tensor([[-0.5722,  0.3781],
        [ 0.0255, -0.0704],
        [ 0.1823,  0.0949],
        [-0.9852,  0.0650]])
tensor([ 2.9543, -0.5630,  1.6056,  1.6421, -0.1631])


In [33]:
W_mbon = torch.normal(mean_mbon, torch.sqrt(1 / (sqrt2 * n_mbon)),
                              generator=None)
print(W_mbon)


tensor([[-0.4541,  0.2105],
        [-0.9273, -0.3542],
        [-0.3912,  0.0674],
        [-0.8747, -0.6640]])


In [19]:
my_dict = {'key1': 1,
          'key2': 'bad',
          'key3': [1, 2, 3]}
print(my_dict['key2'])
print(my_dict)
for key in my_dict:
    print(key)


bad
{'key1': 1, 'key2': 'bad', 'key3': [1, 2, 3]}
key1
key2
key3


In [20]:
vals = [1, 3, 4]
for i in range(6):
    if i in vals:
        print(i)


1
3
4


In [21]:
mbons = [1, 13]
for n in mbons:
    print('There are this many mbons {}'.format(str(n).zfill(2)))
    

There are this many mbons 01
There are this many mbons 13
